#!/usr/bin/env -S podman-compose -f

services:
  davmail:
    image: kran0/telegram-bot-api:latest

    build:
      context: .
      dockerfile: Containerfile
#      args:
#        BRANCH: "master"
#        COMMIT: "d091a73"
    env-file: .env # set TELEGRAM_API_ID and TELEGRAM_API_HASH
    command: # run kran0/telegram-bot-api:latest --help to get help message
#      - --local                        # allow the Bot API server to serve local requests
#      - --http-port=<arg>              # HTTP listening port (default is 8081)
#      - --http-stat-port=<arg>         # HTTP statistics port
      - --dir=/tmp                    # server working directory
      - --temp-dir=/tmp               # directory for storing HTTP server temporary files
#      - --filter=<arg>                 # "<remainder>/<modulo>". Allow only bots with 'bot_user_id % modulo == remainder'
#      - --max-webhook-connections=<arg># default value of the maximum webhook connections per bot
#      - --log=<arg>                    # path to the file where the log will be written
#      - --verbosity=<arg>              # log verbosity level
#      - --memory-verbosity=<arg>       # memory log verbosity level; defaults to 3
#      - --log-max-file-size=<arg>      # maximum size of the log file in bytes before it will be auto-rotated (default is 2000000000)
#      - --max-connections=<arg>        # maximum number of open file descriptors
#      - --cpu-affinity=<arg>           # CPU affinity as 64-bit mask (defaults to all available CPUs)
#      - --main-thread-affinity=<arg>   # CPU affinity of the main thread as 64-bit mask (defaults to the value of the option --cpu-affinity)
#      - --proxy=<arg>                  # HTTP proxy server for outgoing webhook requests in the format http://host:por
    user: 1100:1100
    ports:
      - 8081:8081
    restart: on-failure
    cap-drop: [ "ALL" ]